Rails.application.routes.draw do
  post '/other/escort' => "other#escort_c"
  get '/other/escort' => "other#escort"
  post "/other/create" => "other#create"

  get "/manager/answer/:id" => "manager#answer"
  get "/manager/show_free" => "manager#show_free"
  post "/manager/login" => "manager#login"
  get "/manager/login" => "manager#login_form"

  post "/question/free" => "question#free_c"
  get "/question/free" => "question#free"
  post "/question/question5_reason_bad" => "question#question5_reason_bad_c"
  get "/question/question5_reason_bad" => "question#question5_reason_bad"
  post "/question/question5_reason_good" => "question#question5_reason_good_c"
  get "/question/question5_reason_good" => "question#question5_reason_good"
  post "/question/question5" => "question#question5_c"
  get "/question/question5" => "question#question5"
  post "/question/question4_guest_room" => "question#question4_guest_room_c"
  get "/question/question4_guest_room" => "question#question4_guest_room"
  post "/question/question4_hotel" => "question#question4_hotel_c"
  get "/question/question4_hotel" => "question#question4_hotel"
  post "/question/question4_breakfast" => "question#question4_breakfast_c"
  get "/question/question4_breakfast" => "question#question4_breakfast"
  post "/question/question4_dinner" => "question#question4_dinner_c"
  get "/question/question4_dinner" => "question#question4_dinner"
  post "/question/question4_aromatherapy" => "question#question4_aromatherapy_c"
  get "/question/question4_aromatherapy" => "question#question4_aromatherapy"
  post "/question/question4_jacuzzi" => "question#question4_jacuzzi_c"
  get "/question/question4_jacuzzi" => "question#question4_jacuzzi"
  post "/question/question4_spring" => "question#question4_spring_c"
  get "/question/question4_spring" => "question#question4_spring"
  post "/question/question4_staff" => "question#question4_staff_c"
  get "/question/question4_staff" => "question#question4_staff"
  post "/question/question123" => "question#question123_c"
  get "/question/question123" => "question#question123"
  post "/question/use" => "question#use_c"
  get "/question/use" => "question#use"
  post  "/question/escort" => "question#escort_c"
  get "/question/escort" => "question#escort"
  post "/question/dinner" => "question#dinner_c"
  get "/question/dinner" => "question#dinner"
  post "/question/profile" => "question#profile_c"
  get "/question/profile" => "question#profile"
  post "/registers/create" => "registers#create"
  get "/registers" => "registers#show"

  get "/last" => "home#last"
  get '/' => "home#top"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
